### ISSUE TITLE
First in-person biocommons coordination meeting

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs-hackathons#5]
### Submitter Name

Reece Hart

### Submitter Affiliation

MyOme

### Submitter Github Handle

reece

### Which event day would the project be offered?

- [X] ISMB 2022 Hackathon Day 1
- [X] ISMB 2022 Hackathon Day 2

### Project Details

The [biocommons](https://github.com/biocommons/biocommons) tools include: 
* [hgvs](https://github.com/biocommons/hgvs), an HGVS parsing, validation, and manipulation library
* [UTA (universal transcript archive)](https://github.com/biocommons/uta), an archive of all transcripts from all sources over time
* [SeqRepo](https://github.com/biocommons/biocommons.seqrepo), a space-efficient archive of human sequences used by the hgvs package for variant validation and normalization

This hackathon project will is the first in-person meeting for biocommons contributors. The preliminary agenda will be:

* Review biocommons governance, community guidelines, and practices
* Review issues and develop a roadmap for each package
* Review and document overall architecture and goals

Note 1: As of March 2022, most of the documents implied above are still being written. Stay tuned.

Note 2: This meeting will be held only if there will be sufficient attendance from key contributors. Please subscribe (at right) to this issue to indicate your intention to attend.

### Required Skills

Desired skills
 
* Python
* Experience with hgvs, uta, and/or seqrepo
* Experience with code architecture
* Sphinx documentation
* Pytest
* Docker
* GitHub actions

**Comment by korikuzma** [comment]
@reece , can we discuss moving [uta_tools](https://github.com/GenomicMedLab/uta-tools) to the biocommons organization? UTA Tools currently has work for getting MANE data and other useful methods that query the UTA database such as translating from transcript exons to genomic coordinates and vice versa.

**Comment by reece** [comment]
@korikuzma Sounds good to me!

**Comment by larrybabb** [comment]
@andreasprlic @wesleygoar  can you put a 1-3 minute pitch on this topic to give at the start of the day to try to entice folks to join in on this? we are planning on having a cutoff of 4 people minimum to officially work as a group on a topic. Every topic lead will pitch.  (sounds like this may be a plan to have a zoom call with reece during the breaks or in the evening etc...)

**Comment by larrybabb** [comment]
We are categorizing this a "discussion topic" more than a hackathon effort. So we will schedule time for this outside of the hackathon.

Can @andreasprlic @wesleygoar and @reece find an hour in the near future.
